# ClickHouse Connection Settings
[clickhouse]
host = "localhost"
port = 9000
user = "default"
password = ""

# Cryo Settings
[cryo]
temp_data_path = "/raid/cryo/temp/"
safe_block_margin = 100

# Chain Configurations
[chains]

[chains.ethereum]
rpc_url = "http://127.0.0.1:8545"
datasets = ["blocks", "transactions", "logs"]

[chains.base]
rpc_url = "http://127.0.0.1:6545"
datasets = ["blocks", "transactions", "logs"]