[project]
name = "cryobase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "clickhouse-connect>=0.8.15",
    "result>=0.17.0",
    "toml>=0.10.2",
    "tqdm>=4.67.1",
    "web3>=7.8.0",
]
